apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django_app.name }}-svc
  labels:
    app: {{ .Values.django_app.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.django_app.name }}
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.node_port }}