# Generated by Django 2.2 on 2021-03-17 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Категория задачи', max_length=200, unique=True, verbose_name='Категория')),
                ('owner', models.ForeignKey(help_text='Укажите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='Владелец категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Быстрое добавление задачи', max_length=280, verbose_name='Задача')),
                ('finish_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время выполнения задачи', verbose_name='Дата')),
                ('category', models.ForeignKey(blank=True, help_text='Укажите категорию', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_category', to='tasks.Category', verbose_name='Категория')),
                ('owner', models.ForeignKey(help_text='Укажите имя', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец задачи')),
            ],
            options={
                'ordering': ('finish_date',),
            },
        ),
    ]
