# Generated by Django 2.2 on 2021-04-04 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Быстрое добавление задачи', max_length=280, verbose_name='Задача')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 4, 4, 17, 4, 39, 506941), help_text='Срок выполнения задачи', verbose_name='Дедлайн')),
                ('priority', models.SmallIntegerField(default=10, help_text='Приоритет выполнения задачи', verbose_name='Приоритет')),
            ],
            options={
                'ordering': ('deadline', 'priority'),
            },
        ),
    ]
