# Generated by Django 2.2 on 2021-04-07 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Категория задачи', max_length=200, unique=True, verbose_name='Категория')),
                ('owner', models.ForeignKey(help_text='Укажите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='Владелец категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Быстрое добавление задачи', max_length=280, verbose_name='Задача')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 16, 48, 37, 709438), help_text='Срок выполнения задачи', verbose_name='Дедлайн')),
                ('priority', models.SmallIntegerField(default=10, help_text='Приоритет выполнения задачи', verbose_name='Приоритет')),
                ('category', models.ForeignKey(blank=True, help_text='Укажите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.Category', verbose_name='Категория')),
                ('owner', models.ForeignKey(help_text='Укажите имя владельца', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец задачи')),
            ],
            options={
                'ordering': ('deadline', 'priority', 'category'),
            },
        ),
    ]
