# Generated by Django 2.2 on 2021-04-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_deadline_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('deadline', 'priority', 'category')},
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(help_text='Укажите имя владельца', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец задачи'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Категория задачи', max_length=200, unique=True, verbose_name='Категория')),
                ('owner', models.ForeignKey(help_text='Укажите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='Владелец категории')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Укажите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.Category', verbose_name='Категория'),
        ),
    ]
