# Generated by Django 2.2 on 2021-04-10 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210408_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Срок выполнения задачи', verbose_name='Дедлайн'),
        ),
    ]
