# Generated by Django 2.2 on 2021-04-10 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210411_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), help_text='Срок выполнения задачи', verbose_name='Дедлайн'),
        ),
    ]
