# Generated by Django 2.2 on 2021-04-01 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 13, 36, 0, 150996), help_text='Срок выполнения задачи', verbose_name='Дедлайн'),
        ),
    ]
