# Generated by Django 2.2 on 2021-04-01 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210401_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('deadline', 'priority')},
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 15, 37, 13, 825616), help_text='Срок выполнения задачи', verbose_name='Дедлайн'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
